### PR TITLE
support ghc 7.10

### PR DESCRIPTION
**Pull request by pacak**

### CODE REVIEW

**Comment by Shimuuar** [comment]
In the end I've added handwritten instances for NFData and decided to not add Generic instances (unless asked to do so). Thank you for bringing up issue

Anyway I've uploaded histogram-fill 0.8.4 on hackage

**Comment by pacak** [comment]
Instance for BinD looks wrong to me - it won't force evaluate doubles
inside, only outer constructor to whnf.

**Comment by Shimuuar** [comment]
All fields of BinD are strict (unpacked even) so it's enough to evaluate to
whnf

**Comment by pacak** [comment]
Actually it's LogBinD

https://github.com/Shimuuar/histogram-fill/blob/master/histogram-fill/Data/Histogram/Bin/LogBinD.hs

**Comment by Shimuuar** [comment]
This is bug. Thank you for pointing it out. I will upload fix soon.

**Comment by Shimuuar** [comment]
0.8.4.1 is on hackage

**Pull request closed without merging**
