### PR TITLE
added adaptable histogram

### PR DESCRIPTION
**Pull request by tonyday567**
Hi,

I was wondering whether variable bin histograms would be a useful addition to the library.  If so, I will make generic versions, and would appreciate any naming convention, style changes or whatever suggestions you may have.

Tony

### CODE REVIEW

**Comment by Shimuuar** [comment]
Yes. I'd gladly merge such pull request. I took only cursory look at code.
I'll make in depth review this evening.

One function which in my opinion doesn't make sense is one for splitting
bins in histograms. It assumes uniform distribution of events in bin.
Usuallyit's not the case. Another way to look at the same issue is:
histogram loses some information about events. We know only it which it
fell not its exact position. To split bin correctly we need recover this
information. I think it should be dropped

**Comment by Shimuuar** [comment]
1. Naming. What does `DU` in `BinDU` stands for? I however don't have good naming ideas so far.

 1. I don't think type class `AdaptableBin` is needed. Are there any other data types which could be instance of it?

 2. It would be nice to have function `fromBin1D :: Bin1D bin ⇒ bin → BinDU`. It could be useful if one want to slightly tweak default binning

 3. CPP language pragma causes build failures with older GHC. 

 4. With specialization to generc vectors NFData instance must be written manually. In GHC 7.10 default definition of `rnf` will be changed. Only way to be compatible is to write it manually.

**Comment by tonyday567** [comment]
Thanks.
Bin splitting:  I'm playing around with various ways to estimate a good split estimation proceedure eg http://www.cse.wustl.edu/~jain/papers/psqr.htm.  So I'm working towards a SplitMethod = Uniform | LinearInterpolation etc?  Having said this, I appreciate the information loss argument - it's a very stong one, and a good criteria for dividing histogram abstraction from associated algorithms.  

Naming:
DU just stood for Double and Unboxed.

If Adaptable is an ok suffix, then BinAdaptable would be a clear replacement for BinDU.  But Adaptable was a description of what I was doing with histograms and bins so might not be the most general.  Other choices I thought of were Adaptive, Variable, Unequal.

I called the bin boundaries `cuts` inside the BinDI module - but they could almost be called `quantiles`.  eg 
    
    fromMedian m = histogram (binDU fromList [-1/0, m, 1/0]) (fromList [0.5,0.5])  

Is it too far a stretch to then go with BinQuantiles?

Everything else is clear - will have a stab at your suggestions once naming is settled.

**Comment by Shimuuar** [comment]
23 Фев 2015 г. 2:33 пользователь "Tony Day" <notifications@github.com>
написал:
>
> Thanks.
> Bin splitting: I'm playing around with various ways to estimate a good
split estimation proceedure eg
http://www.cse.wustl.edu/~jain/papers/psqr.htm. So I'm working towards a
SplitMethod = Uniform | LinearInterpolation etc? Having said this, I
appreciate the information loss argument - it's a very stong one, and a
good criteria for dividing histogram abstraction from associated algorithms.
>
I think that histograms could be thought as. We divide data sample into N
subsamples based on their position and calculate some statistics for each
subsample(bin). Usually it's just count but any statistic will do. This
view assumes that binning doesn't changes during histogram collection.

I think that splitting of bins in immutable histograms only means that they
were chosen wrong in the first place. Main reason for building histogram is
data compression. Full data set is too big to work with directly so we want
to squeeze it into fixed amount of data.

I didn't read paper but it seems that your goal is estimation of quantiles
in fixed space. If I'm right you're approaching problem from wrong angle. I
should be expressible as left fold (likely monadic)

**Comment by Shimuuar** [comment]
#### Paper

I skimmed paper and if you trying to implement something similar to described algorithm I think you're on wrong track. Paper quite clearly describes incremental accumulation of data in accumulator of fixed size, in haskell it could be realized as left fold (monadic left fold if accumulator is modified in place).

In this library monadic folds are implemented as HBuilderM (and HBuilder wrapper). Fold structure is somewhat implicit and I'm trying to expose it. Other libraries which explore this idiom (but focus on pure folds are: `folds` and `foldl`)

I think for this pull request it's prudent to merge only new data type for binning and leave out bin splitting in histograms At least for now. New binning algorithm is clearly useful doesn't have any problems

#### Naming 

I think BinQuantile is completely wrong. Quantile is characteristic of distribution and binning is division of domain of distribution in number of sets. It could make sense in context of paper you've mentioned but not in general case.

`BinVariable` is probably best option. Defining feature of binning algorithm is ability to work with arbitrary bins. Or `BinArbitrary`

**Comment by tonyday567** [comment]
BinVariable
---

BinVariable it is.  

> If I'm right you're approaching problem from wrong angle.
Wouldn't surprise me!

Variable Histogram
---
Will separate out Histogram.Adaptable.

What I'm trying to do is a lot broader than the paper (though I am trying to calculate quantiles as well).

Overall, it would be better characterised as wanting to do a fold over streaming data into a histogram, without specifying the bins in advance.  I'm using foldl and have a histogram as the accumulator - see incAdaptiveHist for the context: http://hackage.haskell.org/package/foldl-incremental-0.2.0.0/docs/Control-Foldl-Incremental-Histogram.html#v:incAdaptiveHist.

Not sure what else you can do within a context of using a pure fold.  I haven't looked closely at immutable versus mutable, but was anticipating I could drop an MHistogram in if performance starts to become an issue.

> Main reason for building histogram is data compression. Full data set is too big to work with directly so we want to squeeze it into fixed amount of data.

This is pretty much what I'm intending.  I need to compress streaming data for further upstream processing and relationship analysis with other streamed data.

**Comment by Shimuuar** [comment]
This is very interesting task and I think it's quite complicated and full of tradeoffs. What I don't like in bin-splitting approach is need to obtain information which is already discarded. Moreover total number of bins shouldn't change. It's determined by storage limitations. This means that bin border will move and this will only make problems with lost information worse. I found it very difficult to reason about such algorithm

More promising approach is to estimate 1/n quantiles in constant space. Usuing someming like described in article you've quoted. This link could of intereset too http://hdrhistogram.org/ It piqued my interest some time ago but I've never got time to understand how does in work. 


Performace-wise pure fold will be very inefficient. Update to the vector requires copying of the whole vector. Because of this histogram-fill uses mutable buffer

**Comment by tonyday567** [comment]
I went with BinVar - it seemed to fit in with the naming conventions in other Bins.  A few items to note:

I had to add an undecidable instance for [this](https://github.com/tonyday567/histogram-fill/commit/513b9835e5d0ad45bec75af38cf8615f095ea75f#diff-93c0228eb0f8dc6518aaaa33d788c76dR38).  Couldn't think of a different way (but I didn't look too hard).

I didn't put anything in fromBin1D to check whether the lower boundary of one bin is the same as the upper boundary of the one before.  BinIntervals are continuous with each bin but there isn't a requirement for the whole range to be continuous.

Should we make a BinVarF etc?  I need a BinVarD for my use case, but that's just `type BinVarD = BinVar Unboxed Double.`

In terms of quantile calculations - yes, I coded up the P2 algorithm and it works very well.  https://github.com/tonyday567/p2algo

But I will still need to bin split and merge.  Yes, if you move a bin boundary then the binning was probably wrong in the first place.  In the first place, however, hasn't happened yet given that I have only one pass over the data to get it right.  So going with a rough guess as to the best bin definition and adjusting as more data arrives is better (for my problem domain) than sticking with a wrong prior.

I think the difference is that I'm focused on information compression rather than fixed storage space.  When I can safely compress information I get a massive time performance pickup.  I can run a 5 bin histogram through a computation rather than a million data say.  But what I dont know right now is if 5 is the right number.

**Comment by Shimuuar** [comment]
Ive merged PR. At the same time I found that test suite is broken so I need to fix it and make some more fixes before I can make a release.

**Pull request merged**
